server:
  port: 8001
spring:
  application:
    name: SmartFactory_cr8_weight
#配置数据源
primary:
  datasource:
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
##    url: jdbc:sqlserver://192.168.1.210:1433;DatabaseName=GB_MaterialDB
#    url: jdbc:sqlserver://192.168.0.111:1433;DatabaseName=GB_MaterialDB
#    username: sa
#    password: sa
#    hikari:
#      maximum-pool-size: 20
#      auto-commit: true
#      idle-timeout: 30000
#      pool-name: DatebookHikariCP
#      max-lifetime: 30000
#      connection-timeout: 60000
#      validation-timeout: 3000
#      login-timeout: 5
#      read-only: false
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      #配置基本属性
      url: jdbc:sqlserver://192.168.0.111:1433;DatabaseName=GB_MaterialDB
      username: sa
      password: 123456
      #配置初始化大小/最小/最大
      initialSize: 1
      minIdle: 1
      maxActive: 20
      #获取连接等待超时时间
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
back:
  datasource:
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      #配置基本属性
      url: jdbc:sqlserver://192.168.0.111:1433;DatabaseName=zt8j_ohoyee_dibang
      username: sa
      password: 123456
      #配置初始化大小/最小/最大
      initialSize: 1
      minIdle: 1
      maxActive: 20
      #获取连接等待超时时间
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
mybatis-plus:
#  mapper-locations: classpath:mybatis/*Mapper.xml
#  global-config:
    #驼峰下划线转换
#    db-column-underline: true

logging:
  config: classpath:logback.xml
#  path: D:/data/mylog
#  file: mylog.log
  level:
    root: INFO
    org.springframework: INFO
#    com:
#      ohoyee:
#        weight:
#          mapper: debug


